title: Programmer's notes
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Some notes on development process optimization from Sr. Java Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ipeonte.github.io/
name: ipeone
github_username: ipeonte

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
 - jekyll-remote-theme
